name: Schedule
on:
  schedule:
    - cron: '0 0 * * *'
env:
  FORCE_COLOR: 1
jobs:
  retain-workflows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Delete gate workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: Gate
          retain_days: 7
          keep_minimum_runs: 1
      - name: Delete schedule workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: Schedule
          retain_days: 7
          keep_minimum_runs: 1
      - name: Delete manual workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: Manual
          retain_days: 0
          keep_minimum_runs: 0
